version: '3'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - shared_data:/app/shared
    ports:
      - '5001:80'

  model:
    build:
      context: ./model
      dockerfile: Dockerfile
    tty: true
    volumes:
      - shared_data:/app/shared

volumes:
  shared_data:
    driver: local
