version: '3'
services:
  python3:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
    - ./:/app
    ports:
      - '5001:80'
    command: python3 -m flask run --host=0.0.0.0 --port=80   # Flaskアプリを実行するコマンド
    environment:
      - FLASK_APP=app.py
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=80

volumes:
  app: